# Generated by Django 6.0.2 on 2026-03-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название машины')),
                ('description', models.TextField(verbose_name='укажите описание машины')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='производитель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('category', models.CharField(choices=[('(А)мини-автомобили', '(А)мини-автомобили'), ('(B)городские автомобили', '(B)городские автомобили'), ('(C)среднеразмерные авто ', '(C)среднеразмерные авто '), ('(D)семейные авто', '(D)семейные авто'), ('(E)бизнес-класс', '(E)бизнес-класс'), ('(F)люксовые', '(F)люксовые'), ('(S)спортивные', '(S)спортивные'), ('(M)минивэны', '(M)минивэны'), ('(J)кроссоверы', '(J)кроссоверы'), ('(SUV)внедорожники', '(SUV)внедорожники')], max_length=100, verbose_name='Категория')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='car_images/', verbose_name='Изображение машины')),
                ('url_car', models.URLField(verbose_name='укажите ссылку на обзор машины')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('facts', models.TextField(verbose_name='Факты')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
