# Generated by Django 6.0.2 on 2026-03-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_of_facts', '0003_car_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
