# Generated by Django 6.0.2 on 2026-03-07 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars_of_facts', '0003_car_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(max_length=100, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='drivers_images/')),
                ('date_of_birth', models.DateField()),
                ('experience', models.IntegerField(verbose_name='Стаж вождения (лет)')),
                ('status_rights', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=50, verbose_name='Наличие водительских прав')),
                ('choose_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='cars_of_facts.car')),
            ],
        ),
    ]
