# Generated by Django 6.0.2 on 2026-03-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='status_rights',
            field=models.CharField(choices=[('Есть', 'Есть'), ('Нет', 'Нет')], max_length=50, verbose_name='Наличие водительских прав'),
        ),
    ]
