# Generated by Django 6.0.2 on 2026-03-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_customuser_age_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
    ]
